---
title: "R Notebook"
output:
  md_document:
    variant: markdown_github
---
```{r}
dataset = rio::import("Exam Anxiety.sav")
data = dataset
```
#  Correlation

## Create a scatterplot matrix

```{r}
jmv::corrMatrix(
  data = dataset,
  vars = vars(Code, Revise, Anxiety, Exam),
  flag = TRUE,
  n = TRUE,
  ci = TRUE,
  plots = TRUE,
  plotDens = TRUE,
  plotStats = TRUE)
```

```{r}

# The pairs and plots functions are part of baseR

# pairs using column numbers
pairs(data[,2:4], pch = 19)

# pairs using formula format
pairs(~Revise + Exam + Anxiety, data=data, pch = 19)

# Plot
plot(data[ , 2:4] , pch=20 , cex=1.5 , col="#69b3a2")


# the ggpairs function is part of GGally package which expands ggplot2 package

library(ggplot2)
library(GGally)

# ggpairs using column numbers
GGally::ggpairs(data,columns=2:4)

# ggpairs using column names
GGally::ggpairs(data,columns=c('Revise','Exam','Anxiety'),lower = list(continuous = "smooth"))

```


